### ISSUE TITLE
Quick question about configuration setting

### ISSUE THREAD

**Issue by progistar** [Wang-kaifei/DBReducer#2]
Hi,

I have a quick question about configuration setting in DBReducer.cfg

1) What kinds of activation_type supported? (e.g., HCD-FTMS)
2) Does it support non-enzymatic condition? 
3) What does "msmsnum=32" mean?

Thanks in advance!

**Comment by Wang-kaifei** [comment]
Hi,

1. The "activation_type" means the type of mass spectrometry data. HCD-FTMS, HCD-ITMS, CID-FTMS and CID-ITMS are supported.
2. In fact, the default of DBReducer is non-specific digestion with Trypsin. This is basically no different from non-enzymatic condition. If you need other specific enzyme digestion types, I can provide a new version later.
3. "msmsnum=" means the number of files for the input dataset.

Feel free to contact me if you have any questions!

**Comment by progistar** [comment]
Thank you for your quick reply.
I am confused the meaning of "non-specific digestion with Trypsin."
It would be grateful if you could give me more specific explanation.

**Comment by Wang-kaifei** [comment]
Sorry for the confusion.
"Non-specific digestion" means that the protein is allowed to be cleaved at any site. Specifically, although trypsin is set, enzymatic cleavage at non-KR amino acids is allowed.

**Comment by progistar** [comment]
I appreciate to your kind reply. It helps me!
